server:
  port: 8080
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/forthproject?characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
  application:
    name: demo-service

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qf.j1902.pojo
  #\u5206\u9875\u63D2\u4EF6config
pagehelper:
#\u8BBE\u7F6E\u6570\u636E\u5E93\u65B9\u8A00
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true
